import React from 'react';
import {
    GiBasket, GiJeweledChalice, GiCauldron, GiScrollUnfurled, GiCrossedSwords,
    GiChest, GiPotionBall, GiSwordman, GiGamepad, GiConsoleController,
    GiSprout, GiFlowerPot, GiCookingPot, GiField, GiButterfly,
    GiSteampunkGoggles, GiCircuitry, GiClick, GiServerRack, GiCyberEye,
    GiKeyboard, GiSpatter, GiHand, GiShield, GiBroadsword, GiAnkh,
    GiWaxSeal, GiControlTower,
    // Lofi
    GiCoffeeBeans, GiCompactDisc, GiMoon, GiSofa, GiCoffeeCup, GiQuill, GiMusicalNotes,
    // Renaissance
    GiBreadSlice, GiImperialCrown, GiHarp, GiTrumpetFlag,
    // Cybercity
    GiRobotGrab, GiLightningHelix, GiVrHeadset, GiMechanicalArm, GiWalkieTalkie, GiSatelliteCommunication
} from 'react-icons/gi';

export const THEMES = {
    'dark-academia': {
        name: 'Dark Academia',
        id: 'dark-academia',
        fontImports: ['Playfair Display', 'Inter', 'Courier Prime'],
        cssVars: {
            '--bg-main': '#0c0a09',
            '--bg-panel': '#141210',
            '--bg-hover': '#1f1a16',
            '--bg-main-rgb': '12, 10, 9',
            '--text-main': '#e8e6e3',
            '--text-muted': '#8c857b',
            '--text-dim': '#837c72',
            '--text-gold': '#cfb53b',
            '--text-highlight': '#ffdd99',
            '--accent-crimson': '#be606b',
            '--accent-red': '#e2707c',
            '--accent-green': '#6f9c8a',
            '--accent-gold': '#cfb53b',
            '--accent-gold-dim': 'rgba(207, 181, 59, 0.18)',
            '--border-gold': '#8a7e57',
            '--border-bright': '#cfb53b',
            '--border-dim': '#6e675a',
            '--active-border': '#cfb53b',
            '--font-display': "'Playfair Display', serif",
            '--font-body': "'Inter', sans-serif",
            '--font-mono': "'Courier Prime', monospace",
            '--font-serif': "'Playfair Display', Georgia, 'Times New Roman', serif",
            '--radius-lg': '8px',
            '--glass-panel': 'rgba(20, 18, 16, 0.95)',
            '--glow-gold': '0 0 10px rgba(207, 181, 59, 0.2)',
            '--bg-texture': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.8\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\' opacity=\'0.07\'/%3E%3C/svg%3E")'
        },
        labels: {
            provisions: 'Provisions',
            larderEmpty: 'The larder is empty.',
            fromTheHearth: 'From The Hearth',
            greetingDefault: 'Traveler',
            goals: 'Aspirations',
            habits: 'Rituals',
            hobbies: 'Pursuits',
            library: 'Archives',
            todos: 'Agendas',
            chores: 'Duty',
            social: 'Register',
            status: 'Observatory',
            statusConfig: 'Calibrate Lens',
            statusEstablish: 'Align Stars',
            nowConsuming: 'Now Examining'
        },
        icons: {
            provisions: <GiBasket />,
            goals: <GiScrollUnfurled />,
            habits: <GiJeweledChalice />,
            hobbies: <GiCauldron />,
            games: <GiCrossedSwords />,
            library: <GiScrollUnfurled />,
            todos: <GiScrollUnfurled />,
            chores: <GiAnkh />,
            social: <GiWaxSeal />,
            status: <GiControlTower />
        }
    },
    'eight-bit': {
        name: '8-Bit Arcade',
        id: 'eight-bit',
        fontImports: ['Press Start 2P'],
        cssVars: {
            '--bg-main': '#000000',
            '--bg-panel': '#222222',
            '--bg-hover': '#444444',
            '--bg-main-rgb': '0, 0, 0',
            '--text-main': '#ffffff',
            '--text-muted': '#aaaaaa',
            '--text-dim': '#898989',
            '--text-gold': '#ffff00',
            '--text-highlight': '#00ffff',
            '--accent-crimson': '#ff5555',
            '--accent-red': '#ff5555',
            '--accent-green': '#00ff00',
            '--accent-gold': '#ffff00',
            '--accent-gold-dim': 'rgba(255, 255, 0, 0.18)',
            '--border-gold': '#ffffff',
            '--border-bright': '#ffffff',
            '--border-dim': '#888888',
            '--active-border': '#ffff00',
            '--font-display': "'Press Start 2P', system-ui",
            '--font-body': "'Press Start 2P', system-ui",
            '--font-mono': "'Press Start 2P', system-ui",
            '--font-serif': "'Press Start 2P', system-ui",
            '--radius-lg': '0px',
            '--glass-panel': 'rgba(34, 34, 34, 0.95)',
            '--glow-gold': '0 0 10px rgba(255, 255, 0, 0.2)',
            '--bg-texture': 'none'
        },
        labels: {
            provisions: 'Inventory',
            larderEmpty: 'Empty Inventory',
            fromTheHearth: 'Crafting Items',
            greetingDefault: 'Player 1',
            goals: 'Quests',
            habits: 'Daily XP',
            hobbies: 'Side Quests',
            library: 'Bestiary',
            todos: 'To-Do List',
            chores: 'Missions',
            social: 'Multiplayer',
            status: 'Mini-Map',
            statusConfig: 'Options',
            statusEstablish: 'Sync',
            nowConsuming: 'Equipped'
        },
        icons: {
            provisions: <GiChest />,
            goals: <GiGamepad />,
            habits: <GiPotionBall />,
            hobbies: <GiSwordman />,
            games: <GiConsoleController />,
            library: <GiScrollUnfurled />,
            todos: <GiKeyboard />,
            chores: <GiShield />,
            social: <GiConsoleController />,
            status: <GiSpatter />
        }
    },
    'cottagecore': {
        name: 'Cottagecore',
        id: 'cottagecore',
        fontImports: ['Loved by the King', 'Crimson Text', 'Courier Prime'],
        cssVars: {
            '--bg-main': '#fdf6e3',
            '--bg-panel': '#fff9eb',
            '--bg-hover': '#f5ecce',
            '--bg-main-rgb': '253, 246, 227',
            '--text-main': '#5c4b37',
            '--text-muted': '#6f6152',
            '--text-dim': '#7d6e5e',
            '--text-gold': '#5f6b3c',
            '--text-highlight': '#8a6449',
            '--accent-crimson': '#a84a4a',
            '--accent-red': '#a3352f',
            '--accent-green': '#41663a',
            '--accent-gold': '#7a6620',
            '--accent-gold-dim': 'rgba(122, 102, 32, 0.18)',
            '--border-gold': '#a08a5e',
            '--border-bright': '#6b5c3f',
            '--border-dim': '#a2865c',
            '--active-border': '#6b5c3f',
            '--font-display': "'Loved by the King', cursive",
            '--font-body': "'Crimson Text', serif",
            '--font-mono': "'Courier Prime', monospace",
            '--font-serif': "'Crimson Text', Georgia, serif",
            '--radius-lg': '16px',
            '--glass-panel': 'rgba(255, 249, 235, 0.95)',
            '--glow-gold': '0 0 10px rgba(122, 102, 32, 0.25)',
            '--bg-texture': "url('https://www.transparenttextures.com/patterns/natural-paper.png')"
        },
        labels: {
            provisions: 'Pantry',
            larderEmpty: 'Checking the cupboards...',
            fromTheHearth: 'Garden Harvest',
            greetingDefault: 'Dear Friend',
            goals: 'Little Dreams',
            habits: 'Gentle Beats',
            hobbies: 'Creative Hours',
            library: 'Bookshelf',
            todos: 'Daily Notes',
            chores: 'Tidying',
            social: 'Company',
            status: 'Window View',
            statusConfig: 'Adjust Curtains',
            statusEstablish: 'Open Sash',
            nowConsuming: 'Cozy Reading'
        },
        icons: {
            provisions: <GiFlowerPot />,
            goals: <GiButterfly />,
            habits: <GiSprout />,
            hobbies: <GiCookingPot />,
            games: <GiField />,
            library: <GiFlowerPot />,
            todos: <GiHand />,
            chores: <GiFlowerPot />,
            social: <GiButterfly />,
            status: <GiField />
        }
    },
    'matrix': {
        name: 'The Matrix',
        id: 'matrix',
        fontImports: ['VT323'],
        cssVars: {
            '--bg-main': '#000000',
            '--bg-panel': '#001100',
            '--bg-hover': '#002200',
            '--bg-main-rgb': '0, 0, 0',
            '--text-main': '#00ff00',
            '--text-muted': '#00b300',
            '--text-dim': '#009a00',
            '--text-gold': '#00ff00',
            '--text-highlight': '#ffffff',
            '--accent-crimson': '#22ff22',
            '--accent-red': '#ff5f5f',
            '--accent-green': '#00ff00',
            '--accent-gold': '#00ff00',
            '--accent-gold-dim': 'rgba(0, 255, 0, 0.18)',
            '--border-gold': '#00ff00',
            '--border-bright': '#66ff66',
            '--border-dim': '#008f00',
            '--active-border': '#66ff66',
            '--font-display': "'VT323', monospace",
            '--font-body': "'VT323', monospace",
            '--font-mono': "'VT323', monospace",
            '--font-serif': "'VT323', monospace",
            '--radius-lg': '0px',
            '--glass-panel': 'rgba(0, 17, 0, 0.95)',
            '--glow-gold': '0 0 10px rgba(0, 255, 0, 0.25)',
            '--bg-texture': 'none'
        },
        labels: {
            provisions: 'Data Packets',
            larderEmpty: 'Null Pointer Exception',
            fromTheHearth: 'Source Code',
            greetingDefault: 'Neo',
            goals: 'Directives',
            habits: 'Loops',
            hobbies: 'Sub-routines',
            library: 'Databanks',
            todos: 'Tasks',
            chores: 'Maintenance',
            social: 'Network',
            status: 'Command Line',
            statusConfig: 'Init Request',
            statusEstablish: 'Jack In',
            nowConsuming: 'Parsing'
        },
        icons: {
            provisions: <GiServerRack />,
            goals: <GiClick />,
            habits: <GiCircuitry />,
            hobbies: <GiCyberEye />,
            games: <GiSteampunkGoggles />,
            library: <GiServerRack />,
            todos: <GiServerRack />,
            chores: <GiSteampunkGoggles />,
            social: <GiClick />,
            status: <GiCyberEye />
        }
    },
    'lofi': {
        name: 'Lofi Study',
        id: 'lofi',
        fontImports: ['Comfortaa', 'Quicksand', 'Courier Prime'],
        cssVars: {
            '--bg-main': '#1a1b26',
            '--bg-panel': '#24283b',
            '--bg-hover': '#2f3549',
            '--bg-main-rgb': '26, 27, 38',
            '--text-main': '#a9b1d6',
            '--text-muted': '#969dc1',
            '--text-dim': '#858db7',
            '--text-gold': '#bb9af7',
            '--text-highlight': '#7aa2f7',
            '--accent-crimson': '#f7768e',
            '--accent-red': '#f7768e',
            '--accent-green': '#9ece6a',
            '--accent-gold': '#bb9af7',
            '--accent-gold-dim': 'rgba(187, 154, 247, 0.18)',
            '--border-gold': '#6f79a8',
            '--border-bright': '#bb9af7',
            '--border-dim': '#69739f',
            '--active-border': '#bb9af7',
            '--font-display': "'Comfortaa', cursive",
            '--font-body': "'Quicksand', sans-serif",
            '--font-mono': "'Courier Prime', monospace",
            '--font-serif': "'Quicksand', sans-serif",
            '--radius-lg': '20px',
            '--glass-panel': 'rgba(36, 40, 59, 0.95)',
            '--glow-gold': '0 0 10px rgba(187, 154, 247, 0.25)',
            '--bg-texture': 'none'
        },
        labels: {
            provisions: 'Essentials',
            larderEmpty: 'Restocking the vibes...',
            fromTheHearth: 'Chill Beats',
            greetingDefault: 'Friend',
            goals: 'Chill Dreams',
            habits: 'Vibes',
            hobbies: 'Side Quests',
            library: 'Vinyls',
            todos: 'Notes',
            chores: 'Tidying',
            social: 'Hangouts',
            status: 'Lo-fi Radio',
            statusConfig: 'Change Station',
            statusEstablish: 'Tune In',
            nowConsuming: 'Vibing'
        },
        icons: {
            provisions: <GiCoffeeBeans />,
            goals: <GiMoon />,
            habits: <GiMusicalNotes />,
            hobbies: <GiSofa />,
            games: <GiGamepad />,
            library: <GiCompactDisc />,
            todos: <GiQuill />,
            chores: <GiFlowerPot />,
            social: <GiCoffeeCup />,
            status: <GiCompactDisc />
        }
    },
    'renaissance': {
        name: 'Renaissance',
        id: 'renaissance',
        fontImports: ['Cinzel', 'Cormorant Garamond', 'Courier Prime'],
        cssVars: {
            '--bg-main': '#0e1111',
            '--bg-panel': '#1a1c1c',
            '--bg-hover': '#2a2d2d',
            '--bg-main-rgb': '14, 17, 17',
            '--text-main': '#d4af37',
            '--text-muted': '#9a9d9d',
            '--text-dim': '#818484',
            '--text-gold': '#ffd700',
            '--text-highlight': '#ffffff',
            '--accent-crimson': '#cf6a6a',
            '--accent-red': '#d46a6a',
            '--accent-green': '#6f9c7a',
            '--accent-gold': '#d4af37',
            '--accent-gold-dim': 'rgba(212, 175, 55, 0.18)',
            '--border-gold': '#d4af37',
            '--border-bright': '#ffd700',
            '--border-dim': '#6a6d6d',
            '--active-border': '#ffd700',
            '--font-display': "'Cinzel', serif",
            '--font-body': "'Cormorant Garamond', serif",
            '--font-mono': "'Courier Prime', monospace",
            '--font-serif': "'Cormorant Garamond', Georgia, serif",
            '--radius-lg': '4px',
            '--glass-panel': 'rgba(26, 28, 28, 0.95)',
            '--glow-gold': '0 0 10px rgba(212, 175, 55, 0.25)',
            '--bg-texture': 'url("https://www.transparenttextures.com/patterns/natural-paper.png")'
        },
        labels: {
            provisions: 'Victuals',
            larderEmpty: 'The cellar is bare.',
            fromTheHearth: 'Artisan Works',
            greetingDefault: 'Noble',
            goals: 'Legacies',
            habits: 'Practices',
            hobbies: 'Mastery',
            library: 'Scriptorium',
            todos: 'Decrees',
            chores: 'Labor',
            social: 'Courts',
            status: 'Heraldry',
            statusConfig: 'Ink Scroll',
            statusEstablish: 'Seal Decree',
            nowConsuming: 'Studying'
        },
        icons: {
            provisions: <GiBreadSlice />,
            goals: <GiImperialCrown />,
            habits: <GiHarp />,
            hobbies: <GiImperialCrown />,
            games: <GiCrossedSwords />,
            library: <GiScrollUnfurled />,
            todos: <GiQuill />,
            chores: <GiAnkh />,
            social: <GiTrumpetFlag />,
            status: <GiImperialCrown />
        }
    },
    'cybercity': {
        name: 'Cybercity',
        id: 'cybercity',
        fontImports: ['Orbitron', 'Michroma', 'Courier Prime'],
        cssVars: {
            '--bg-main': '#050505',
            '--bg-panel': '#0d0d0d',
            '--bg-hover': '#1a1a1a',
            '--bg-main-rgb': '5, 5, 5',
            '--text-main': '#00f3ff',
            '--text-muted': '#a15cff',
            '--text-dim': '#994eff',
            '--text-gold': '#ff00ae',
            '--text-highlight': '#ffffff',
            '--accent-crimson': '#ff003c',
            '--accent-red': '#ff3860',
            '--accent-green': '#00ff9f',
            '--accent-gold': '#ff00ae',
            '--accent-gold-dim': 'rgba(255, 0, 174, 0.18)',
            '--border-gold': '#00f3ff',
            '--border-bright': '#00f3ff',
            '--border-dim': '#00868c',
            '--active-border': '#00f3ff',
            '--font-display': "'Orbitron', sans-serif",
            '--font-body': "'Michroma', sans-serif",
            '--font-mono': "'Courier Prime', monospace",
            '--font-serif': "'Michroma', sans-serif",
            '--radius-lg': '0px',
            '--glass-panel': 'rgba(13, 13, 13, 0.95)',
            '--glow-gold': '0 0 10px rgba(255, 0, 174, 0.25)',
            '--bg-texture': 'linear-gradient(rgba(0,0,0,0.9), rgba(0,0,0,0.9)), repeating-linear-gradient(transparent, transparent 2px, rgba(0, 243, 255, 0.05) 3px)'
        },
        labels: {
            provisions: 'Hardware',
            larderEmpty: 'System Resource Low',
            fromTheHearth: 'Firmware',
            greetingDefault: 'User',
            goals: 'Milestones',
            habits: 'Processes',
            hobbies: 'Mod-Lines',
            library: 'Data-Banks',
            todos: 'Logs',
            chores: 'Cleanup',
            social: 'Comms',
            status: 'Uplink',
            statusConfig: 'Re-Link',
            statusEstablish: 'Go Live',
            nowConsuming: 'Executing'
        },
        icons: {
            provisions: <GiRobotGrab />,
            goals: <GiLightningHelix />,
            habits: <GiCircuitry />,
            hobbies: <GiVrHeadset />,
            games: <GiSteampunkGoggles />,
            library: <GiServerRack />,
            todos: <GiMechanicalArm />,
            chores: <GiCircuitry />,
            social: <GiWalkieTalkie />,
            status: <GiSatelliteCommunication />
        }
    }
};
